### PR TITLE
Snapshots Data Masking

### PR DESCRIPTION
**Pull request by jonhopper-dataengineers**
added the ability to apply data masking to snapshot tables.

we needed to be able to apply table data masking which has been created via a snapshot. modified the "models" path to include "model" and "snapshot"  as the resource types.

added in the snapshots post-hook into the docs to be able to apply the mask.

### CODE REVIEW

**Comment by entechlog** [comment]
@jonhopper-dataengineers, Thank You for the change. Do you also have the ability to include test results to this PR ?

**Comment by jonhopper-dataengineers** [comment]
> @jonhopper-dataengineers,
> 
> * Thank You for the change
> * Reviewed the changes visually and is looking good
> * Do you also have the ability to include test results to this PR ?

I have added a snapshot and applied the masking to it .. is that what you meant?
image

email address was used as the column for the mask ... so it follows the functionality in the model example of the same data

**Comment by entechlog** [comment]
@jonhopper-dataengineers , Yes and Thank You. Did you also test removing mask as well ?

**Comment by jonhopper-dataengineers** [comment]
> @jonhopper-dataengineers , Yes and Thank You. Did you also test removing mask as well ?

Yes I did. Works a treat.

**Comment by entechlog** [comment]
Thanks @jonhopper-dataengineers , Merging this change now and will create a release

**Review by entechlog — APPROVED** [review]

**Pull request merged**
